import type { FeatureDefinition } from "./types"

export const featureDefinitions: FeatureDefinition[] = [
  {
    name: "utility_on_time_ratio",
    type: "ratio",
    description: "Share of simulated utility bills paid on or before the due date.",
    source: "utility",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with a missing-data warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "utility",
  },
  {
    name: "utility_missed_payment_rate",
    type: "ratio",
    description: "Share of simulated utility bills missed in the observation window.",
    source: "utility",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with a missing-data warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "utility",
  },
  {
    name: "utility_amount_volatility",
    type: "index",
    description: "Volatility of utility bill amounts after normalizing for seasonal changes.",
    source: "utility",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Set to moderate volatility when utility data is unavailable.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "utility",
  },
  {
    name: "utility_observation_months",
    type: "months",
    description: "Months of simulated utility behavior available.",
    source: "utility",
    direction: "positive",
    range: [0, 12],
    missingDataBehavior: "Missing months reduce data coverage rather than acting as a hard negative.",
    appearsInCustomerExplanation: false,
    usedByModel: true,
    category: "coverage",
  },
  {
    name: "telecom_recharge_regularity",
    type: "ratio",
    description: "Consistency of simulated telecom recharges or bill payments.",
    source: "telecom",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation when telecom source is off.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "telecom",
  },
  {
    name: "telecom_account_tenure_months",
    type: "months",
    description: "Simulated telecom account continuity in months.",
    source: "telecom",
    direction: "positive",
    range: [0, 72],
    missingDataBehavior: "Missing tenure lowers coverage only.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "tenure",
  },
  {
    name: "telecom_failed_payment_rate",
    type: "ratio",
    description: "Failed simulated telecom payments divided by all telecom payments.",
    source: "telecom",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "telecom",
  },
  {
    name: "wallet_inflow_regularity",
    type: "ratio",
    description: "Regularity of simulated wallet inflows without rewarding high volume alone.",
    source: "jazzcash",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation when wallet data is unavailable.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "wallet",
  },
  {
    name: "wallet_outflow_volatility",
    type: "index",
    description: "Volatility of simulated wallet outflows.",
    source: "easypaisa",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Moderate volatility imputation.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "wallet",
  },
  {
    name: "wallet_balance_stability",
    type: "ratio",
    description: "Stability of simulated wallet balances over time.",
    source: "easypaisa",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "wallet",
  },
  {
    name: "wallet_failed_transaction_rate",
    type: "ratio",
    description: "Failed simulated wallet transactions divided by all wallet transactions.",
    source: "jazzcash",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "wallet",
  },
  {
    name: "bill_payment_consistency",
    type: "ratio",
    description: "Combined consistency across simulated bill payment behavior.",
    source: "cashflow",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Falls back to available utility and wallet signals.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "financial",
  },
  {
    name: "simulated_repayment_ratio",
    type: "ratio",
    description: "Share of simulated installments completed successfully.",
    source: "repayment",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation when no repayment history exists.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "repayment",
  },
  {
    name: "simulated_days_late_average",
    type: "count",
    description: "Average days late on simulated repayments.",
    source: "repayment",
    direction: "negative",
    range: [0, 45],
    missingDataBehavior: "Zero only when repayment records explicitly show on-time behavior; otherwise neutral.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "repayment",
  },
  {
    name: "cash_flow_coverage",
    type: "ratio",
    description: "Simulated ratio of stable inflows to committed outflows.",
    source: "cashflow",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with coverage penalty.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "financial",
  },
  {
    name: "income_stability",
    type: "ratio",
    description: "Regularity of simulated income timing and recurrence.",
    source: "cashflow",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Neutral imputation with warning.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "financial",
  },
  {
    name: "expense_volatility",
    type: "index",
    description: "Month-to-month volatility of simulated expenses.",
    source: "cashflow",
    direction: "negative",
    range: [0, 1],
    missingDataBehavior: "Moderate volatility imputation.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "financial",
  },
  {
    name: "negative_balance_days",
    type: "count",
    description: "Simulated days with cash-flow shortfalls.",
    source: "cashflow",
    direction: "negative",
    range: [0, 30],
    missingDataBehavior: "Neutral imputation with coverage penalty.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "financial",
  },
  {
    name: "account_age_months",
    type: "months",
    description: "Synthetic financial relationship age.",
    source: "profile",
    direction: "positive",
    range: [0, 84],
    missingDataBehavior: "Missing value lowers confidence.",
    appearsInCustomerExplanation: false,
    usedByModel: true,
    category: "tenure",
  },
  {
    name: "data_completeness",
    type: "ratio",
    description: "Completeness of all simulated source data available for scoring.",
    source: "profile",
    direction: "positive",
    range: [0, 1],
    missingDataBehavior: "Calculated from available source records.",
    appearsInCustomerExplanation: true,
    usedByModel: true,
    category: "coverage",
  },
]

export const featureByName = Object.fromEntries(featureDefinitions.map((feature) => [feature.name, feature]))

export const modelFeatureNames = featureDefinitions.filter((feature) => feature.usedByModel).map((feature) => feature.name)
