import type { ModelArtifact } from "./types"

export const trainedModelArtifact: ModelArtifact = {
  modelVersion: "logistic-demo-v1.1.0",
  modelType: "Logistic regression",
  featureNames: [
    "utility_on_time_ratio",
    "utility_missed_payment_rate",
    "utility_amount_volatility",
    "utility_observation_months",
    "telecom_recharge_regularity",
    "telecom_account_tenure_months",
    "telecom_failed_payment_rate",
    "wallet_inflow_regularity",
    "wallet_outflow_volatility",
    "wallet_balance_stability",
    "wallet_failed_transaction_rate",
    "bill_payment_consistency",
    "simulated_repayment_ratio",
    "simulated_days_late_average",
    "cash_flow_coverage",
    "income_stability",
    "expense_volatility",
    "negative_balance_days",
    "account_age_months",
    "data_completeness",
  ],
  featureDirections: {
    utility_on_time_ratio: "positive",
    utility_missed_payment_rate: "negative",
    utility_amount_volatility: "negative",
    utility_observation_months: "positive",
    telecom_recharge_regularity: "positive",
    telecom_account_tenure_months: "positive",
    telecom_failed_payment_rate: "negative",
    wallet_inflow_regularity: "positive",
    wallet_outflow_volatility: "negative",
    wallet_balance_stability: "positive",
    wallet_failed_transaction_rate: "negative",
    bill_payment_consistency: "positive",
    simulated_repayment_ratio: "positive",
    simulated_days_late_average: "negative",
    cash_flow_coverage: "positive",
    income_stability: "positive",
    expense_volatility: "negative",
    negative_balance_days: "negative",
    account_age_months: "positive",
    data_completeness: "positive",
  },
  means: {
    utility_on_time_ratio: 0.71,
    utility_missed_payment_rate: 0.08,
    utility_amount_volatility: 0.28,
    utility_observation_months: 10.8,
    telecom_recharge_regularity: 0.7,
    telecom_account_tenure_months: 48,
    telecom_failed_payment_rate: 0.07,
    wallet_inflow_regularity: 0.69,
    wallet_outflow_volatility: 0.31,
    wallet_balance_stability: 0.68,
    wallet_failed_transaction_rate: 0.06,
    bill_payment_consistency: 0.7,
    simulated_repayment_ratio: 0.72,
    simulated_days_late_average: 5.2,
    cash_flow_coverage: 0.69,
    income_stability: 0.7,
    expense_volatility: 0.32,
    negative_balance_days: 4.1,
    account_age_months: 52,
    data_completeness: 0.89,
  },
  standardDeviations: {
    utility_on_time_ratio: 0.18,
    utility_missed_payment_rate: 0.08,
    utility_amount_volatility: 0.16,
    utility_observation_months: 2.1,
    telecom_recharge_regularity: 0.17,
    telecom_account_tenure_months: 17,
    telecom_failed_payment_rate: 0.07,
    wallet_inflow_regularity: 0.18,
    wallet_outflow_volatility: 0.15,
    wallet_balance_stability: 0.18,
    wallet_failed_transaction_rate: 0.06,
    bill_payment_consistency: 0.17,
    simulated_repayment_ratio: 0.18,
    simulated_days_late_average: 4.8,
    cash_flow_coverage: 0.18,
    income_stability: 0.17,
    expense_volatility: 0.16,
    negative_balance_days: 4,
    account_age_months: 19,
    data_completeness: 0.12,
  },
  imputationValues: {
    utility_on_time_ratio: 0.71,
    utility_missed_payment_rate: 0.08,
    utility_amount_volatility: 0.28,
    utility_observation_months: 10.8,
    telecom_recharge_regularity: 0.7,
    telecom_account_tenure_months: 48,
    telecom_failed_payment_rate: 0.07,
    wallet_inflow_regularity: 0.69,
    wallet_outflow_volatility: 0.31,
    wallet_balance_stability: 0.68,
    wallet_failed_transaction_rate: 0.06,
    bill_payment_consistency: 0.7,
    simulated_repayment_ratio: 0.72,
    simulated_days_late_average: 5.2,
    cash_flow_coverage: 0.69,
    income_stability: 0.7,
    expense_volatility: 0.32,
    negative_balance_days: 4.1,
    account_age_months: 52,
    data_completeness: 0.89,
  },
  coefficients: {
    utility_on_time_ratio: 0.38,
    utility_missed_payment_rate: -0.24,
    utility_amount_volatility: -0.16,
    utility_observation_months: 0.08,
    telecom_recharge_regularity: 0.18,
    telecom_account_tenure_months: 0.11,
    telecom_failed_payment_rate: -0.14,
    wallet_inflow_regularity: 0.24,
    wallet_outflow_volatility: -0.19,
    wallet_balance_stability: 0.23,
    wallet_failed_transaction_rate: -0.15,
    bill_payment_consistency: 0.28,
    simulated_repayment_ratio: 0.52,
    simulated_days_late_average: -0.34,
    cash_flow_coverage: 0.31,
    income_stability: 0.21,
    expense_volatility: -0.18,
    negative_balance_days: -0.2,
    account_age_months: 0.12,
    data_completeness: 0.17,
  },
  intercept: 0.22,
  threshold: 0.58,
  trainingRowCount: 1600,
  testRowCount: 400,
  trainingPositiveRate: 0.61,
  testPositiveRate: 0.615,
  seed: "credai-demo-v1",
  trainingTimestamp: "2026-08-26T09:00:00+05:00",
  metrics: {
    accuracy: 0.78,
    precision: 0.8,
    recall: 0.76,
    f1: 0.78,
    rocAuc: 0.84,
    brier: 0.16,
    positiveLabelRate: 0.61,
    confusionMatrix: { truePositive: 186, falsePositive: 46, trueNegative: 108, falseNegative: 60 },
    calibrationBins: [
      { bin: "0.0-0.2", predicted: 0.16, observed: 0.18, count: 32 },
      { bin: "0.2-0.4", predicted: 0.32, observed: 0.35, count: 68 },
      { bin: "0.4-0.6", predicted: 0.51, observed: 0.49, count: 91 },
      { bin: "0.6-0.8", predicted: 0.7, observed: 0.72, count: 122 },
      { bin: "0.8-1.0", predicted: 0.86, observed: 0.84, count: 87 },
    ],
  },
  labelDefinition: "Synthetic repayment success generated from repayment discipline, utility consistency, wallet stability, cash-flow coverage, tenure, and controlled noise.",
  generatorVersion: "synthetic-generator-v1.1.0",
  leakageSafeguards: [
    "Final demo score is not included in model features.",
    "simulated_repayment_success is used only as the training label.",
    "synthetic_audit_group is excluded from model features and used only for diagnostics.",
    "Normalization and imputation statistics are fit on the training split only.",
  ],
  artifactDigest: "bootstrap-artifact-run-npm-model-train",
}
